/// Flutter icons MenuCustom
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuCustom
///      fonts:
///       - asset: fonts/MenuCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MenuCustom {
  MenuCustom._();

  static const _kFontFam = 'MenuCustom';
  static const String _kFontPkg = null;

  static const IconData menu = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourites = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shape = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
